const actionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  PLUS_CART_ITEM: 'PLUS_CART_ITEM',
  MINUS_CART_ITEM: 'MINUS_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  SAVE_ACTIVE_CATEGORY: 'SAVE_ACTIVE_CATEGORY',
  CHANGE_CURRENCY: 'CHANGE_CURRENCY',
  SET_CURRENT_ID: 'SET_CURRENT_ID',
  SET_FILTER_NAME: 'SET_FILTER_NAME',
  SET_FILTER_INDEX: 'SET_FILTER_INDEX',
  CHANGE_OVERLAY_FlAG: 'CHANGE_OVERLAY_FLAG',
  SET_ATTRIBUTES: 'CHANGE_ATTRIBUTES',
};
export default actionTypes;
